[0m15:26:46.592449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107082a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10898b140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10898ae70>]}


============================== 15:26:46.596142 | 063b0377-5700-454d-8cb1-4dc59e480478 ==============================
[0m15:26:46.596142 [info ] [MainThread]: Running with dbt=1.9.6
[0m15:26:46.596486 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/ediland/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init test_dbt_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:26:46.605452 [debug] [MainThread]: Starter project path: /Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt-env/lib/python3.12/site-packages/dbt/include/starter_project
[0m15:26:46.609539 [info ] [MainThread]: 
Your new dbt project "test_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:26:46.609777 [info ] [MainThread]: Setting up your profile.
[0m15:31:38.382032 [info ] [MainThread]: Profile test_dbt_project written to /Users/ediland/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:31:38.388301 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 291.83408, "process_in_blocks": "0", "process_kernel_time": 0.168276, "process_mem_max_rss": "128172032", "process_out_blocks": "0", "process_user_time": 0.817143}
[0m15:31:38.390373 [debug] [MainThread]: Command `dbt init` succeeded at 15:31:38.390118 after 291.84 seconds
[0m15:31:38.390988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10898b260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b320c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109627f50>]}
[0m15:31:38.391527 [debug] [MainThread]: Flushing usage events
[0m15:31:38.737634 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:31:52.767568 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1043402c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104ed72c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104ed6ff0>]}


============================== 15:31:52.770490 | 4cee4abe-7f06-4d97-a142-f8ee38eac319 ==============================
[0m15:31:52.770490 [info ] [MainThread]: Running with dbt=1.9.6
[0m15:31:52.770807 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/ediland/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:31:52.778819 [info ] [MainThread]: dbt version: 1.9.6
[0m15:31:52.779069 [info ] [MainThread]: python version: 3.12.7
[0m15:31:52.779217 [info ] [MainThread]: python path: /Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt-env/bin/python
[0m15:31:52.779351 [info ] [MainThread]: os info: macOS-15.5-arm64-arm-64bit
[0m15:31:52.953338 [info ] [MainThread]: Using profiles dir at /Users/ediland/.dbt
[0m15:31:52.953617 [info ] [MainThread]: Using profiles.yml file at /Users/ediland/.dbt/profiles.yml
[0m15:31:52.953824 [info ] [MainThread]: Using dbt_project.yml file at /Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt_project.yml
[0m15:31:52.954011 [info ] [MainThread]: Configuration:
[0m15:31:52.954158 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m15:31:52.954291 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:31:52.954421 [info ] [MainThread]: Required dependencies:
[0m15:31:52.954593 [debug] [MainThread]: Executing "git --help"
[0m15:31:52.969913 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m15:31:52.970494 [debug] [MainThread]: STDERR: "b''"
[0m15:31:52.970692 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m15:31:52.970867 [info ] [MainThread]: Connection test skipped since no profile was found
[0m15:31:52.971098 [info ] [MainThread]: [31m2 checks failed:[0m
[0m15:31:52.971236 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "my-snowflake-db", target "dev" invalid: 'database' is a required property


[0m15:31:52.971406 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt_project.yml> not found

[0m15:31:52.973533 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.24058467, "process_in_blocks": "0", "process_kernel_time": 0.143542, "process_mem_max_rss": "128122880", "process_out_blocks": "0", "process_user_time": 0.779345}
[0m15:31:52.974283 [debug] [MainThread]: Command `dbt debug` failed at 15:31:52.974220 after 0.24 seconds
[0m15:31:52.974573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a16b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10578acc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a7a120>]}
[0m15:31:52.974820 [debug] [MainThread]: Flushing usage events
[0m15:31:53.235144 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:57:26.296732 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104806e70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077ef200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077eef30>]}


============================== 11:57:26.300141 | d6049938-e345-4d9c-9eb5-eee754b1facd ==============================
[0m11:57:26.300141 [info ] [MainThread]: Running with dbt=1.9.6
[0m11:57:26.300479 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ediland/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:57:26.300946 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:57:26.302826 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.053394668, "process_in_blocks": "0", "process_kernel_time": 0.137549, "process_mem_max_rss": "103677952", "process_out_blocks": "0", "process_user_time": 0.686022}
[0m11:57:26.303093 [debug] [MainThread]: Command `dbt deps` failed at 11:57:26.303043 after 0.05 seconds
[0m11:57:26.303294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10763c8f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106ec1970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077efe30>]}
[0m11:57:26.303460 [debug] [MainThread]: Flushing usage events
[0m11:57:26.616178 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:13:42.707646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106758dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085ef6b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085ef3e0>]}


============================== 11:13:42.711080 | 5bcaab4a-ae63-4b6a-914a-13d75dfeff22 ==============================
[0m11:13:42.711080 [info ] [MainThread]: Running with dbt=1.9.6
[0m11:13:42.711442 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ediland/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build -s tasty_bytes_daily_hamburg_sales', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:13:42.711786 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:13:42.713400 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04320425, "process_in_blocks": "0", "process_kernel_time": 0.114432, "process_mem_max_rss": "103383040", "process_out_blocks": "0", "process_user_time": 0.667673}
[0m11:13:42.713715 [debug] [MainThread]: Command `dbt build` failed at 11:13:42.713655 after 0.04 seconds
[0m11:13:42.713911 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079f26c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085ef7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085ef770>]}
[0m11:13:42.714090 [debug] [MainThread]: Flushing usage events
[0m11:13:42.989819 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:44:19.926909 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1069565a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f2f260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f2efc0>]}


============================== 18:44:19.929164 | d446a6cc-86df-43dd-8196-eb49cfcbf1f1 ==============================
[0m18:44:19.929164 [info ] [MainThread]: Running with dbt=1.9.6
[0m18:44:19.929489 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ediland/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build --select state:modified --state /Users/ediland/Documents/state_artifacts/', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:44:19.929784 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ediland/Documents/GitHub/dbt_snowflake_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:44:19.931014 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.03564558, "process_in_blocks": "0", "process_kernel_time": 0.084976, "process_mem_max_rss": "104087552", "process_out_blocks": "0", "process_user_time": 0.631507}
[0m18:44:19.931294 [debug] [MainThread]: Command `dbt build` failed at 18:44:19.931241 after 0.04 seconds
[0m18:44:19.931483 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106eeccb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f2f170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f2f140>]}
[0m18:44:19.931643 [debug] [MainThread]: Flushing usage events
[0m18:44:20.145763 [debug] [MainThread]: An error was encountered while trying to flush usage events
